version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: lobanmatin
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: savrdb
    ports:
      - "5432:5432"
  test:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/savrdb
      SPRING_DATASOURCE_USERNAME: lobanmatin
      SPRING_DATASOURCE_PASSWORD: yourpassword
    depends_on:
      - postgres
    command: mvn test
