spring.application.name=savr

# Temporarily disable datasource auto config (remove this when adding DB)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

