CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL DEFAULT 'USER'
);

CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    total_income NUMERIC(38,2) NOT NULL,
    total_limit NUMERIC(38,2) NOT NULL,
    CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    amount NUMERIC(38,2) NOT NULL,
    category VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE budget_category_limits (
    budget_id BIGINT NOT NULL,
    category VARCHAR(255) NOT NULL,
    category_limit NUMERIC(38,2),
    PRIMARY KEY (budget_id, category),
    CONSTRAINT fk_budget_category_limits_budget FOREIGN KEY (budget_id) REFERENCES budgets(id) ON DELETE CASCADE
);
